{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError"},"topicSections":[{"generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/network(_:)","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/unknown(isProtected:)"],"anchor":"Enumeration-Cases"},{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/errorDescription"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/Error-Implementations","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/LocalizedError-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConnectionError"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.github.pulse\/documentation\/Pulse","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger"]]},"variants":[{"paths":["\/documentation\/pulse\/remotelogger\/connectionerror"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.github.pulse\/10Foundation14LocalizedErrorP","doc:\/\/com.github.pulse\/s5ErrorP","doc:\/\/com.github.pulse\/s8SendableP"],"kind":"relationships"}],"metadata":{"title":"RemoteLogger.ConnectionError","externalID":"s:5Pulse12RemoteLoggerC15ConnectionErrorO","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConnectionError"}],"modules":[{"name":"Pulse"}],"symbolKind":"enum","role":"symbol","navigatorTitle":[{"text":"ConnectionError","kind":"identifier"}],"roleHeading":"Enumeration"},"references":{"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError/unknown(isProtected:)":{"role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"},{"kind":"text","text":"("},{"text":"isProtected","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"abstract":[],"title":"RemoteLogger.ConnectionError.unknown(isProtected:)","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/unknown(isProtected:)","kind":"symbol","url":"\/documentation\/pulse\/remotelogger\/connectionerror\/unknown(isprotected:)"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError/network(_:)":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"network"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NWError","preciseIdentifier":"s:7Network7NWErrorO"},{"kind":"text","text":")"}],"title":"RemoteLogger.ConnectionError.network(_:)","role":"symbol","url":"\/documentation\/pulse\/remotelogger\/connectionerror\/network(_:)","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/network(_:)","abstract":[],"kind":"symbol"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError/Error-Implementations":{"kind":"article","title":"Error Implementations","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/Error-Implementations","type":"topic","role":"collectionGroup","abstract":[],"url":"\/documentation\/pulse\/remotelogger\/connectionerror\/error-implementations"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError/LocalizedError-Implementations":{"role":"collectionGroup","type":"topic","abstract":[],"title":"LocalizedError Implementations","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/LocalizedError-Implementations","kind":"article","url":"\/documentation\/pulse\/remotelogger\/connectionerror\/localizederror-implementations"},"doc://com.github.pulse/s5ErrorP":{"title":"Swift.Error","type":"unresolvable","identifier":"doc:\/\/com.github.pulse\/s5ErrorP"},"doc://com.github.pulse/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.github.pulse\/s8SendableP"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError/errorDescription":{"title":"errorDescription","type":"topic","url":"\/documentation\/pulse\/remotelogger\/connectionerror\/errordescription","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/errorDescription","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"role":"symbol","kind":"symbol","abstract":[]},"doc://com.github.pulse/10Foundation14LocalizedErrorP":{"title":"Foundation.LocalizedError","type":"unresolvable","identifier":"doc:\/\/com.github.pulse\/10Foundation14LocalizedErrorP"},"doc://com.github.pulse/documentation/Pulse":{"role":"collection","url":"\/documentation\/pulse","kind":"symbol","title":"Pulse","abstract":[{"type":"text","text":"Logger and network inspector for Apple platforms."}],"identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse","type":"topic"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError":{"identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError","title":"RemoteLogger.ConnectionError","abstract":[],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConnectionError"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConnectionError"}],"kind":"symbol","url":"\/documentation\/pulse\/remotelogger\/connectionerror"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger":{"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RemoteLogger","kind":"identifier"}],"identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger","title":"RemoteLogger","role":"symbol","url":"\/documentation\/pulse\/remotelogger","abstract":[{"type":"text","text":"Connects to the remote server and sends logs remotely. In the current version,"},{"type":"text","text":" "},{"text":"a server is a Pulse Pro app for macOS).","type":"text"}],"navigatorTitle":[{"text":"RemoteLogger","kind":"identifier"}]}}}