{"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"code":"LocalizedError.failureReason","type":"codeVoice"},{"type":"text","text":"."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/failureReason","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pulse\/remotelogger\/connectionerror\/failurereason"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.github.pulse\/documentation\/Pulse","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/LocalizedError-Implementations"]]},"metadata":{"title":"failureReason","roleHeading":"Instance Property","role":"symbol","modules":[{"name":"Pulse","relatedModules":["Foundation"]}],"symbolKind":"property","extendedModule":"Foundation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"platforms":[{"unavailable":false,"beta":false,"name":"iOS","deprecated":false,"introducedAt":"8.0"},{"beta":false,"unavailable":false,"deprecated":false,"name":"iPadOS","introducedAt":"8.0"},{"name":"Mac Catalyst","beta":false,"introducedAt":"8.0","unavailable":false,"deprecated":false},{"introducedAt":"10.10","name":"macOS","unavailable":false,"deprecated":false,"beta":false},{"introducedAt":"9.0","deprecated":false,"name":"tvOS","unavailable":false,"beta":false},{"introducedAt":"2.0","beta":false,"name":"watchOS","unavailable":false,"deprecated":false}],"externalID":"s:10Foundation14LocalizedErrorPAAE13failureReasonSSSgvp::SYNTHESIZED::s:5Pulse12RemoteLoggerC15ConnectionErrorO"},"references":{"doc://com.github.pulse/documentation/Pulse":{"title":"Pulse","url":"\/documentation\/pulse","abstract":[{"text":"Logger and network inspector for Apple platforms.","type":"text"}],"role":"collection","type":"topic","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse","kind":"symbol"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError/LocalizedError-Implementations":{"type":"topic","kind":"article","title":"LocalizedError Implementations","url":"\/documentation\/pulse\/remotelogger\/connectionerror\/localizederror-implementations","role":"collectionGroup","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/LocalizedError-Implementations","abstract":[]},"doc://com.github.pulse/documentation/Pulse/RemoteLogger":{"navigatorTitle":[{"kind":"identifier","text":"RemoteLogger"}],"url":"\/documentation\/pulse\/remotelogger","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RemoteLogger","kind":"identifier"}],"kind":"symbol","title":"RemoteLogger","abstract":[{"type":"text","text":"Connects to the remote server and sends logs remotely. In the current version,"},{"text":" ","type":"text"},{"type":"text","text":"a server is a Pulse Pro app for macOS)."}],"role":"symbol"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError/failureReason":{"kind":"symbol","type":"topic","role":"symbol","title":"failureReason","url":"\/documentation\/pulse\/remotelogger\/connectionerror\/failurereason","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/failureReason","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError":{"navigatorTitle":[{"kind":"identifier","text":"ConnectionError"}],"type":"topic","kind":"symbol","abstract":[],"title":"RemoteLogger.ConnectionError","role":"symbol","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError","url":"\/documentation\/pulse\/remotelogger\/connectionerror","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConnectionError"}]}}}