{"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"LocalizedError.helpAnchor"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"helpAnchor"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.github.pulse\/documentation\/Pulse","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/LocalizedError-Implementations"]]},"variants":[{"paths":["\/documentation\/pulse\/remotelogger\/connectionerror\/helpanchor"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"roleHeading":"Instance Property","externalID":"s:10Foundation14LocalizedErrorPAAE10helpAnchorSSSgvp::SYNTHESIZED::s:5Pulse12RemoteLoggerC15ConnectionErrorO","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"helpAnchor","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"modules":[{"relatedModules":["Foundation"],"name":"Pulse"}],"role":"symbol","title":"helpAnchor","platforms":[{"deprecated":false,"unavailable":false,"introducedAt":"8.0","beta":false,"name":"iOS"},{"introducedAt":"8.0","beta":false,"name":"iPadOS","deprecated":false,"unavailable":false},{"name":"Mac Catalyst","beta":false,"introducedAt":"8.0","unavailable":false,"deprecated":false},{"deprecated":false,"introducedAt":"10.10","beta":false,"name":"macOS","unavailable":false},{"unavailable":false,"name":"tvOS","introducedAt":"9.0","beta":false,"deprecated":false},{"introducedAt":"2.0","deprecated":false,"beta":false,"unavailable":false,"name":"watchOS"}],"extendedModule":"Foundation"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/helpAnchor","interfaceLanguage":"swift"},"references":{"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError/LocalizedError-Implementations":{"type":"topic","kind":"article","title":"LocalizedError Implementations","url":"\/documentation\/pulse\/remotelogger\/connectionerror\/localizederror-implementations","role":"collectionGroup","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/LocalizedError-Implementations","abstract":[]},"doc://com.github.pulse/documentation/Pulse":{"title":"Pulse","url":"\/documentation\/pulse","abstract":[{"text":"Logger and network inspector for Apple platforms.","type":"text"}],"role":"collection","type":"topic","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse","kind":"symbol"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger":{"navigatorTitle":[{"kind":"identifier","text":"RemoteLogger"}],"url":"\/documentation\/pulse\/remotelogger","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RemoteLogger","kind":"identifier"}],"kind":"symbol","title":"RemoteLogger","abstract":[{"type":"text","text":"Connects to the remote server and sends logs remotely. In the current version,"},{"text":" ","type":"text"},{"type":"text","text":"a server is a Pulse Pro app for macOS)."}],"role":"symbol"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError":{"navigatorTitle":[{"kind":"identifier","text":"ConnectionError"}],"type":"topic","kind":"symbol","abstract":[],"title":"RemoteLogger.ConnectionError","role":"symbol","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError","url":"\/documentation\/pulse\/remotelogger\/connectionerror","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConnectionError"}]},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError/helpAnchor":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"helpAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"kind":"symbol","title":"helpAnchor","type":"topic","role":"symbol","url":"\/documentation\/pulse\/remotelogger\/connectionerror\/helpanchor","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/helpAnchor","abstract":[]}}}