{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/LocalizedError-Implementations"},"kind":"article","metadata":{"roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"Pulse"}],"title":"LocalizedError Implementations"},"hierarchy":{"paths":[["doc:\/\/com.github.pulse\/documentation\/Pulse","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError"]]},"sections":[],"variants":[{"paths":["\/documentation\/pulse\/remotelogger\/connectionerror\/localizederror-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"identifiers":["doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/failureReason","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/helpAnchor","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/recoverySuggestion"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"}],"references":{"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError/failureReason":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/failureReason","url":"\/documentation\/pulse\/remotelogger\/connectionerror\/failurereason","abstract":[],"title":"failureReason","kind":"symbol"},"doc://com.github.pulse/documentation/Pulse":{"role":"collection","url":"\/documentation\/pulse","kind":"symbol","title":"Pulse","abstract":[{"type":"text","text":"Logger and network inspector for Apple platforms."}],"identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse","type":"topic"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError":{"identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError","title":"RemoteLogger.ConnectionError","abstract":[],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConnectionError"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConnectionError"}],"kind":"symbol","url":"\/documentation\/pulse\/remotelogger\/connectionerror"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger":{"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RemoteLogger","kind":"identifier"}],"identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger","title":"RemoteLogger","role":"symbol","url":"\/documentation\/pulse\/remotelogger","abstract":[{"type":"text","text":"Connects to the remote server and sends logs remotely. In the current version,"},{"type":"text","text":" "},{"text":"a server is a Pulse Pro app for macOS).","type":"text"}],"navigatorTitle":[{"text":"RemoteLogger","kind":"identifier"}]},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError/helpAnchor":{"url":"\/documentation\/pulse\/remotelogger\/connectionerror\/helpanchor","title":"helpAnchor","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"helpAnchor","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/helpAnchor","kind":"symbol","role":"symbol","abstract":[]},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError/recoverySuggestion":{"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[],"title":"recoverySuggestion","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/recoverySuggestion","kind":"symbol","url":"\/documentation\/pulse\/remotelogger\/connectionerror\/recoverysuggestion"}}}