{"variants":[{"paths":["\/documentation\/pulse\/remotelogger\/connectionerror\/localizederror-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/LocalizedError-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/failureReason","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/helpAnchor","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/recoverySuggestion"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Pulse"}],"role":"collectionGroup","title":"LocalizedError Implementations"},"hierarchy":{"paths":[["doc:\/\/com.github.pulse\/documentation\/Pulse","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError"]]},"references":{"doc://com.github.pulse/documentation/Pulse/RemoteLogger":{"role":"symbol","title":"RemoteLogger","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemoteLogger"}],"abstract":[{"type":"text","text":"Connects to the remote server and sends logs remotely. In the current version,"},{"type":"text","text":" "},{"type":"text","text":"a server is a Pulse Pro app for macOS)."}],"identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RemoteLogger"}],"url":"\/documentation\/pulse\/remotelogger"},"doc://com.github.pulse/documentation/Pulse":{"role":"collection","title":"Pulse","abstract":[{"type":"text","text":"Logger and network inspector for Apple platforms."}],"identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse","kind":"symbol","type":"topic","url":"\/documentation\/pulse"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError/failureReason":{"role":"symbol","title":"failureReason","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/failureReason","kind":"symbol","type":"topic","url":"\/documentation\/pulse\/remotelogger\/connectionerror\/failurereason"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError/recoverySuggestion":{"role":"symbol","title":"recoverySuggestion","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/recoverySuggestion","kind":"symbol","type":"topic","url":"\/documentation\/pulse\/remotelogger\/connectionerror\/recoverysuggestion"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError":{"role":"symbol","title":"RemoteLogger.ConnectionError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConnectionError"}],"abstract":[],"identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConnectionError"}],"url":"\/documentation\/pulse\/remotelogger\/connectionerror"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError/helpAnchor":{"role":"symbol","title":"helpAnchor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"helpAnchor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/helpAnchor","kind":"symbol","type":"topic","url":"\/documentation\/pulse\/remotelogger\/connectionerror\/helpanchor"}}}