{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pulse\/remotelogger\/connectionerror\/network(_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.github.pulse\/documentation\/Pulse","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError"]]},"kind":"symbol","metadata":{"title":"RemoteLogger.ConnectionError.network(_:)","roleHeading":"Case","symbolKind":"case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"network"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NWError","preciseIdentifier":"s:7Network7NWErrorO"},{"kind":"text","text":")"}],"modules":[{"name":"Pulse"}],"externalID":"s:5Pulse12RemoteLoggerC15ConnectionErrorO7networkyAE7Network7NWErrorOcAEmF"},"identifier":{"url":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/network(_:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"network"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:7Network7NWErrorO","text":"NWError","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.github.pulse/documentation/Pulse/RemoteLogger":{"abstract":[{"type":"text","text":"Connects to the remote server and sends logs remotely. In the current version,"},{"type":"text","text":" "},{"text":"a server is a Pulse Pro app for macOS).","type":"text"}],"role":"symbol","url":"\/documentation\/pulse\/remotelogger","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RemoteLogger","kind":"identifier"}],"kind":"symbol","title":"RemoteLogger","navigatorTitle":[{"kind":"identifier","text":"RemoteLogger"}],"identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError/network(_:)":{"role":"symbol","type":"topic","url":"\/documentation\/pulse\/remotelogger\/connectionerror\/network(_:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"network"},{"text":"(","kind":"text"},{"text":"NWError","kind":"typeIdentifier","preciseIdentifier":"s:7Network7NWErrorO"},{"kind":"text","text":")"}],"title":"RemoteLogger.ConnectionError.network(_:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/network(_:)"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError":{"role":"symbol","navigatorTitle":[{"text":"ConnectionError","kind":"identifier"}],"type":"topic","url":"\/documentation\/pulse\/remotelogger\/connectionerror","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConnectionError"}],"title":"RemoteLogger.ConnectionError","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError"},"doc://com.github.pulse/documentation/Pulse":{"kind":"symbol","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse","url":"\/documentation\/pulse","abstract":[{"type":"text","text":"Logger and network inspector for Apple platforms."}],"type":"topic","title":"Pulse","role":"collection"}}}