{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failures"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/PulseCore\/documentation\/PulseCore\/NetworkLoggerInsights\/FailuresInfo","preciseIdentifier":"s:9PulseCore21NetworkLoggerInsightsC12FailuresInfoV","text":"FailuresInfo"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/pulsecore\/networkloggerinsights\/failures"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/PulseCore\/documentation\/PulseCore\/NetworkLoggerInsights\/failures","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failures"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FailuresInfo","preciseIdentifier":"s:9PulseCore21NetworkLoggerInsightsC12FailuresInfoV"}],"title":"failures","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:9PulseCore21NetworkLoggerInsightsC8failuresAC12FailuresInfoVvp","modules":[{"name":"PulseCore"}]},"hierarchy":{"paths":[["doc:\/\/PulseCore\/documentation\/PulseCore","doc:\/\/PulseCore\/documentation\/PulseCore\/NetworkLoggerInsights"]]},"references":{"doc://PulseCore/documentation/PulseCore":{"role":"collection","title":"PulseCore","abstract":[{"type":"text","text":"Logger and network inspector for Apple platforms."}],"identifier":"doc:\/\/PulseCore\/documentation\/PulseCore","kind":"symbol","type":"topic","url":"\/documentation\/pulsecore"},"doc://PulseCore/documentation/PulseCore/NetworkLoggerInsights/failures":{"role":"symbol","title":"failures","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failures"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FailuresInfo","preciseIdentifier":"s:9PulseCore21NetworkLoggerInsightsC12FailuresInfoV"}],"abstract":[],"identifier":"doc:\/\/PulseCore\/documentation\/PulseCore\/NetworkLoggerInsights\/failures","kind":"symbol","type":"topic","url":"\/documentation\/pulsecore\/networkloggerinsights\/failures"},"doc://PulseCore/documentation/PulseCore/NetworkLoggerInsights/FailuresInfo":{"role":"symbol","title":"NetworkLoggerInsights.FailuresInfo","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FailuresInfo"}],"abstract":[],"identifier":"doc:\/\/PulseCore\/documentation\/PulseCore\/NetworkLoggerInsights\/FailuresInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FailuresInfo"}],"url":"\/documentation\/pulsecore\/networkloggerinsights\/failuresinfo"},"doc://PulseCore/documentation/PulseCore/NetworkLoggerInsights":{"role":"symbol","title":"NetworkLoggerInsights","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkLoggerInsights"}],"abstract":[{"type":"text","text":"Collects insights about the current session."}],"identifier":"doc:\/\/PulseCore\/documentation\/PulseCore\/NetworkLoggerInsights","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NetworkLoggerInsights"}],"url":"\/documentation\/pulsecore\/networkloggerinsights"}}}