{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@NSManaged"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDomain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/pulsecore\/loggernetworkrequestentity\/errordomain"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/PulseCore\/documentation\/PulseCore\/LoggerNetworkRequestEntity\/errorDomain","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDomain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"errorDomain","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@PulseCore@objc(cs)LoggerNetworkRequestEntity(py)errorDomain","modules":[{"name":"PulseCore"}]},"hierarchy":{"paths":[["doc:\/\/PulseCore\/documentation\/PulseCore","doc:\/\/PulseCore\/documentation\/PulseCore\/LoggerNetworkRequestEntity"]]},"references":{"doc://PulseCore/documentation/PulseCore/LoggerNetworkRequestEntity/errorDomain":{"role":"symbol","title":"errorDomain","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDomain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/PulseCore\/documentation\/PulseCore\/LoggerNetworkRequestEntity\/errorDomain","kind":"symbol","type":"topic","url":"\/documentation\/pulsecore\/loggernetworkrequestentity\/errordomain"},"doc://PulseCore/documentation/PulseCore":{"role":"collection","title":"PulseCore","abstract":[{"type":"text","text":"Logger and network inspector for Apple platforms."}],"identifier":"doc:\/\/PulseCore\/documentation\/PulseCore","kind":"symbol","type":"topic","url":"\/documentation\/pulsecore"},"doc://PulseCore/documentation/PulseCore/LoggerNetworkRequestEntity":{"role":"symbol","title":"LoggerNetworkRequestEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggerNetworkRequestEntity"}],"abstract":[],"identifier":"doc:\/\/PulseCore\/documentation\/PulseCore\/LoggerNetworkRequestEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LoggerNetworkRequestEntity"}],"url":"\/documentation\/pulsecore\/loggernetworkrequestentity"}}}