{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"unknownError","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/pulse\/loggerstore\/error\/unknownerror"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.github.pulse\/documentation\/Pulse\/LoggerStore\/Error\/unknownError"},"metadata":{"roleHeading":"Case","title":"LoggerStore.Error.unknownError","modules":[{"name":"Pulse"}],"externalID":"s:5Pulse11LoggerStoreC5ErrorO07unknownD0yA2EmF","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unknownError"}],"role":"symbol","symbolKind":"case"},"hierarchy":{"paths":[["doc:\/\/com.github.pulse\/documentation\/Pulse","doc:\/\/com.github.pulse\/documentation\/Pulse\/LoggerStore","doc:\/\/com.github.pulse\/documentation\/Pulse\/LoggerStore\/Error"]]},"references":{"doc://com.github.pulse/documentation/Pulse/LoggerStore":{"title":"LoggerStore","abstract":[{"type":"text","text":"Persistently stores logs, network requests, and response blobs."}],"url":"\/documentation\/pulse\/loggerstore","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggerStore"}],"identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/LoggerStore","navigatorTitle":[{"text":"LoggerStore","kind":"identifier"}],"kind":"symbol"},"doc://com.github.pulse/documentation/Pulse":{"title":"Pulse","url":"\/documentation\/pulse","abstract":[{"text":"Logger and network inspector for Apple platforms.","type":"text"}],"role":"collection","type":"topic","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse","kind":"symbol"},"doc://com.github.pulse/documentation/Pulse/LoggerStore/Error":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/LoggerStore\/Error","type":"topic","title":"LoggerStore.Error","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Error"}],"url":"\/documentation\/pulse\/loggerstore\/error","navigatorTitle":[{"kind":"identifier","text":"Error"}],"abstract":[]},"doc://com.github.pulse/documentation/Pulse/LoggerStore/Error/unknownError":{"url":"\/documentation\/pulse\/loggerstore\/error\/unknownerror","title":"LoggerStore.Error.unknownError","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknownError"}],"kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/LoggerStore\/Error\/unknownError","role":"symbol"}}}