{"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknownError"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"unknownError","kind":"identifier"}],"title":"LoggerStore.Error.unknownError","symbolKind":"case","externalID":"s:5Pulse11LoggerStoreC5ErrorO07unknownD0yA2EmF","roleHeading":"Case","modules":[{"name":"Pulse"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.github.pulse\/documentation\/Pulse","doc:\/\/com.github.pulse\/documentation\/Pulse\/LoggerStore","doc:\/\/com.github.pulse\/documentation\/Pulse\/LoggerStore\/Error"]]},"variants":[{"paths":["\/documentation\/pulse\/loggerstore\/error\/unknownerror"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.github.pulse\/documentation\/Pulse\/LoggerStore\/Error\/unknownError","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"references":{"doc://com.github.pulse/documentation/Pulse/LoggerStore/Error/unknownError":{"abstract":[],"title":"LoggerStore.Error.unknownError","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"unknownError","kind":"identifier"}],"url":"\/documentation\/pulse\/loggerstore\/error\/unknownerror","kind":"symbol","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/LoggerStore\/Error\/unknownError","type":"topic","role":"symbol"},"doc://com.github.pulse/documentation/Pulse/LoggerStore":{"type":"topic","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/LoggerStore","abstract":[{"text":"Persistently stores logs, network requests, and response blobs.","type":"text"}],"url":"\/documentation\/pulse\/loggerstore","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"LoggerStore","kind":"identifier"}],"navigatorTitle":[{"text":"LoggerStore","kind":"identifier"}],"title":"LoggerStore","role":"symbol"},"doc://com.github.pulse/documentation/Pulse/LoggerStore/Error":{"title":"LoggerStore.Error","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Error"}],"navigatorTitle":[{"kind":"identifier","text":"Error"}],"identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/LoggerStore\/Error","url":"\/documentation\/pulse\/loggerstore\/error","abstract":[],"role":"symbol","type":"topic","kind":"symbol"},"doc://com.github.pulse/documentation/Pulse":{"kind":"symbol","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse","url":"\/documentation\/pulse","abstract":[{"type":"text","text":"Logger and network inspector for Apple platforms."}],"type":"topic","title":"Pulse","role":"collection"}}}