{"hierarchy":{"paths":[["doc:\/\/com.github.pulse\/documentation\/Pulse","doc:\/\/com.github.pulse\/documentation\/Pulse\/LoggerStore","doc:\/\/com.github.pulse\/documentation\/Pulse\/LoggerStore\/Error"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.github.pulse\/documentation\/Pulse\/LoggerStore\/Error\/unknownError"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"unknownError","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/pulse\/loggerstore\/error\/unknownerror"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"title":"LoggerStore.Error.unknownError","modules":[{"name":"Pulse"}],"role":"symbol","externalID":"s:5Pulse11LoggerStoreC5ErrorO07unknownD0yA2EmF","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"unknownError","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"references":{"doc://com.github.pulse/documentation/Pulse/LoggerStore":{"kind":"symbol","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/LoggerStore","url":"\/documentation\/pulse\/loggerstore","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggerStore"}],"role":"symbol","type":"topic","title":"LoggerStore","abstract":[{"text":"Persistently stores logs, network requests, and response blobs.","type":"text"}],"navigatorTitle":[{"text":"LoggerStore","kind":"identifier"}]},"doc://com.github.pulse/documentation/Pulse/LoggerStore/Error":{"abstract":[],"type":"topic","title":"LoggerStore.Error","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Error"}],"navigatorTitle":[{"text":"Error","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/LoggerStore\/Error","url":"\/documentation\/pulse\/loggerstore\/error","role":"symbol"},"doc://com.github.pulse/documentation/Pulse":{"role":"collection","url":"\/documentation\/pulse","kind":"symbol","title":"Pulse","abstract":[{"type":"text","text":"Logger and network inspector for Apple platforms."}],"identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse","type":"topic"},"doc://com.github.pulse/documentation/Pulse/LoggerStore/Error/unknownError":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknownError","kind":"identifier"}],"abstract":[],"title":"LoggerStore.Error.unknownError","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/LoggerStore\/Error\/unknownError","role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/pulse\/loggerstore\/error\/unknownerror"}}}